### ISSUE TITLE
8.0 Still out of date

### ISSUE THREAD

**Issue by Gorthezar** [lqnrd/LookingForSatchels#2]
I updated to 8.0 release but it is still showing as out of date

![image](https://user-images.githubusercontent.com/20695078/42957555-e3a876f0-8b37-11e8-9cf9-b5aa8bf55381.png)

**Comment by lqnrd** [comment]
Thanks for the issue report, this is now changed with the latest commit d2841883003b21e9a3d359edfa6fddcc9bed3a83, and should be live on Curse in a couple of minutes.

Usually an addon will still be usable even if shown as "out of date". This simply means that the toc-version number was not updated to the latest ingame version.
